### ISSUE TITLE
How to do SR inference only

### ISSUE THREAD

**Issue by Oguzhanercan** [JaehaKim97/SR4IR#3]
I want to see the SR results, but the test code is not working for that. How can easily hack the code for just sr inference. It is a little bit complicated.

**Comment by JaehaKim97** [comment]
Hi @Oguzhanercan.

I think the easiest way to perform SR inference only is to comment out the recognition network's forwarding process.
For example, in the classification setting, you can do such a thing by modifying the [evaluation function](https://github.com/JaehaKim97/SR4IR/blob/4b2c3a7a963e7538a1065b4d7097a78e33978186/src/models/cls/sr4ir_cls_model.py#L190C5-L190C51) as follows:

```
def evaluate(self, data_loader_test, epoch=0):
   ...
   # pred_sr = self.net_cls(self.normalize(img_sr))  # Comment out L209
   ...
   # acc1_sr, _ = calculate_accuracy(pred_sr, label, topk=(1, 5))  # Comment out L222
   # metric_logger.meters["acc1_sr"].update(acc1_sr.item(), n=batch_size)  # Comment out L223
   ...
   # metric_summary = self.add_metric(metric_summary, 'ACC_SR@1', metric_logger.acc1_sr.global_avg, epoch)  # Comment out L246
```

Then, you can do SR inference only with the below command:
```
CUDA_VISIBLE_DEVICES=0 python src/main.py -opt options/cls/StanfordCars/124_SR4IR_edsr_x8.yml --test_only --visualize
```

You can also do similar things in segmentation and detection.

**Comment by Oguzhanercan** [comment]
Thanks a lot.
